code-squad/homepage

index.html, sync.sh
1. Applied google analytics 
2. Simple s3 upload script
=> Feature GA

src/components/Avatar/Avatar.test.tsx, src/components/DropdownItem/DropdownItem.test.tsx, src/components/DropdownItem/DropdownItem.tsx, src/components/DropdownItem/index.ts, src/components/InterviewBox/InterviewBox.tsx, src/components/InterviewBox/index.ts, src/components/InterviewBox/interviewBox.test.tsx, src/components/index.ts, src/lib/context/GlobalTheme.tsx, src/lib/testUtils/TestProvider.tsx, src/lib/testUtils/index.ts, src/pages/index.tsx, src/styles/theme.ts
* Provider에 사용되는 타입 수정
* TestProvider추가
=> ✨ 220429: 테마수정, 테스트코드 유틸 추가, dropdown기능 제작

scripts/jest/jest.config.ts, src/components/DropdownItem/DropdownItem.test.tsx, src/components/DropdownItem/DropdownItem.tsx, src/components/InterviewBox/InterviewBox.tsx, src/components/LinkButton/LinkButton.test.tsx, src/components/LinkButton/LinkButton.tsx, src/components/LinkButton/index.ts, src/components/index.ts, src/styles/style.d.ts, src/typography/index.tsx
* config module의 위치를 잡지 못해 발생하는 테스트버그 수정
* 글로벌하게 사용되는 테마에 타입 추가
=> ✨ 220502: 테스트 설정 수정, 테마타입 추가, 링크버튼 컴포넌트 제작

.storybook/main.js, .storybook/preview.js, package-lock.json, package.json, src/components/Avatar/Avatar.stories.tsx, src/components/ImageCard/ImageCard.stories.tsx, src/components/ImageCard/ImageCard.test.tsx, src/components/ImageCard/ImageCard.tsx
=> 📦 220509: 스토리북 패키지 추가 및 실행되도록 수정

src/components/BannerPopup/BannerPopup.stories.tsx, src/components/CircleNavigation/CircleNavigation.stories.tsx, src/components/CircleNavigation/CircleNavigation.tsx, src/components/Footer/Footer.stories.tsx, src/components/Footer/Footer.test.tsx, src/components/HomeGlobalNavigationBar/HomeGlobalNavigationBar.stories.tsx, src/components/MButton/MButton.stories.tsx, src/components/MButton/MButton.tsx, src/components/SButton/SButton.stories.tsx, src/components/SButton/SButton.tsx, src/components/TabNavigationBar/TabNavigationBar.stories.tsx, src/components/TabNavigationBar/TabNavigationBar.tsx, src/components/TagNavigationBar/TagNavigationBar.stories.tsx, src/components/TeamGlobalNavigationBar/TeamGlobalNavigationBar.stories.tsx
* #29 에 정의되어있는 컴포넌트들
* 기획서대로 UI가 보여지지 않는 컴포넌트들을 수정
* MButton, SButton, CircleNavigation
* 중복되는 테스트 케이스들을 배열을 사용하여 하나의 케이스에서 테스트되도록 수정
=> ✨ 220510: 각 컴포넌트의 스토리 제작

content/code-together/registration.mdx, content/javascript/registrations.mdx, content/masters/registration.mdx, src/components/Registration/Registration.tsx, src/components/Registration/index.tsx, src/components/index.ts, src/pageComponents/code-together/Course/Course.tsx, src/pageComponents/code-together/Masthead/Masthead.tsx, src/pageComponents/javascript/Registration/Registration.tsx, src/pageComponents/masters/MastersRegistration/MastersRegistration.tsx, src/pageComponents/masters/MastersRegistration/index.tsx, src/pageComponents/masters/index.ts, src/pages/code-together/index.tsx, src/pages/masters/index.tsx
=> ♻️ 220527: Registration 공용 컴포넌트 제작, 마스터즈 페이지에서 Registration 컴포넌트를 렌더링하도록 개선, 자바스크립트 페이지에서 Registration 컴포넌트를 사용하도록 수정

build-storybook.log, package-lock.json, scripts/jest/jest.config.js, src/lib/context/Layout.tsx
* 잘못된 package-lock.json파일 수정
* jest.config파일에 ignore추가
* 잘못 작성된 세미콜론 제거
=> 🐛 220616: 패키지 에러 수정, 세미콜론 제거

.github/CODEOWNERS, .github/workflows/pipeline-beta.yml
=> ✨ 220616: github action workflow 제작

src/styles/GlobalStyle.tsx
=> 🔧 220620: body, main 의 최소 크기를 100vh로 변경

.github/workflows/pipeline-master.yml
=> ✨ 220620: master 브랜치용 github action 제작

src/components/HomeGlobalNavigationBar/HomeGlobalNavigationBar.tsx, src/pageComponents/main/Banner/Banner.test.tsx, src/pageComponents/main/Banner/Banner.tsx, src/pageComponents/main/Banner/Banner.type.ts, src/pages/index.tsx
=> 🔧 220620: 배너와 헤더 컴포넌트의 위치 수정

src/assets/static/phrases.ts, src/components/Footer/Footer.tsx, src/pageComponents/code-together/Masthead/Masthead.tsx, src/pageComponents/masters/Masthead/Masthead.tsx
* 이메일 옆 | 문구 제거
* Masthead 크기 조정
=> 🔧 220620: 피드백 적용

src/pageComponents/main/Banner/Banner.tsx, src/pages/index.tsx
* 쿠키를 통해 배너가 안보이도록 하는 기능 로컬스토리지를 사용하도록 수정
* https://github.com/code-squad/homepage/issues/131
=> :bug: 220630: 배너 버그 수정

src/lib/testUtils/index.ts, src/lib/testUtils/removeCookie.ts, src/pageComponents/main/Banner/Banner.test.tsx
=> 🧪 220630: 로컬스토리지 테스트 추가

src/pageComponents/main/Banner/Banner.tsx, src/pages/index.tsx
=> :bug: 220630: localStorage 빌드에러 수정

src/pageComponents/main/Banner/Banner.test.tsx, src/pageComponents/main/Banner/Banner.tsx, src/pages/index.tsx
=> 🔧 220701: 배너 버그 수정

src/assets/static/phrases.ts, src/pageComponents/main/Place/Place.tsx
* 공간 이미지 부분을 주소, 화살표부분까지 꽉 찰수 있도록 사이즈 변경 
* #138 
* 자바스크립트 코스의 -> 자바스크립트 과정의로 문구 수정
=> 🔧 220708: 공간 이미지 크기 변경, 문구 수정

src/lib/context/GlobalHeader.tsx
=> :sparkles: 220711: 탭에 표시되는 제목이 올바르게 표시되도록 수정

src/styles/fonts.css
=> 🔧 220824: 불필요한 폰트 옵션 제거

src/lib/context/GlobalHeader.tsx
=> 🔧 220826: window 객체가 undefined인치 확인하고 조건문을 처리하도록 수정

src/components/HomeGlobalNavigationBar/HomeGlobalNavigationBar.tsx, src/components/InterviewBox/InterviewBox.tsx
=> 🐛 220826: 인터뷰 박스의 크기가 고정되는 문제 수정, 모바일 타겟에서 GNB의 버튼들이 잠깐 보여지는 현상 수정 

package-lock.json, package.json, src/components/HomeGlobalNavigationBar/HomeGlobalNavigationBar.tsx, src/lib/hooks/useResponsive.ts, src/pageComponents/main/Culture/Culture.tsx, src/pageComponents/main/Place/Place.tsx, src/pageComponents/main/Welcome/Welcome.tsx
* Culture, Place 영역에 Swipe 인터렉션 적용
=> 🔧 220830: Swipe 인터렉션 적용

src/pageComponents/main/Feature/Feature.tsx, src/typography/index.tsx
* type에 해당되는 styled-component를 반환하는 Typography 컴포넌트 제작
* 메인 페이지의 Feature 페이지 컴포넌트에 일부 적용
=> ✨ 220830: Typography 컴포넌트 제작

src/components/TagNavigationBar/TagNavigationBar.tsx, src/pageComponents/faq/FAQ/FAQ.tsx
=> 🔧 220831: FAQ페이지 반응형 UI 작업

src/pageComponents/notFound/NotFound/NotFound.tsx
=> 💄 220902: 404페이지 반응형 추가

src/assets/img/img.stories.tsx, src/components/CourseInfo/InfoItem/InfoItem.tsx, src/components/DropdownItem/DropdownItem.tsx, src/components/Footer/Footer.tsx, src/pageComponents/javascript/DetailCurriculum/Curriculum/Curriculum.tsx, src/pageComponents/javascript/DetailCurriculum/Curriculum/MasterInfo/MasterInfo.tsx, src/pageComponents/team-culture/TeamCulture/TeamCulture.tsx, src/typography/index.tsx
=> 🔧 220902: 신규 Typography 컴포넌트를 통해 문자들을 렌더링하도록 수정

src/components/TitleSet/TitleSet.tsx
=> 💄 220902: TitleSet 컴포넌트의 불필요한 스타일 설정 코드 제거

src/components/TabNavigationBar/TabNavigationBar.tsx, src/pageComponents/masters/DetailCurriculum/DetailCurriculum.tsx
=> 🔧 220902: 네비게이터가 클릭되었을 때 스크롤이 움직이는 기능 추가

src/lib/hooks/useResponsive.ts
=> 🔧 220902: 상태에서 불필요한 값이 관리되지 않도록 수정

src/lib/context/GlobalHeader.tsx
=> 🔧 220902: 불필요한 viewport 설정 코드 제거

src/styles/fonts.css
* font가 로딩되기 전에는 글자가 보여지지 않도록 옵션 설정
=> 💄 220902: font-display 옵션 설정

src/components/MButton/MButton.tsx, src/lib/hooks/useResponsive.ts, src/lib/hooks/useScrollPosition.ts, src/pages/index.tsx, src/typography/index.tsx
* 리액트 컴포넌트에서 `typeof window === "undefined"` 에 의해 발생
* useResponsive훅이 한번 실행된 이후 useEffect()를 통해 window객체에서 크기를 얻어와 responsive 객체를 반환하도록 수정
* Typography 에서 isMobile / isTablet / isDesktop 이 모두 false이면 null을 반환
* 모바일/태블릿 환경에서 hover를 적용하면 클릭 후 hover상태의 스타일링이 적용되어있음.
=> 🔧 220902: Minified React Error 수정, 최초 렌더링시 글자 크기가 변하는 현상 수정, 모바일/태블릿 환경에서 버튼 클릭시 색상이 변경되도록 수정, 스크롤이동 훅의 쓰로틀링이 제대로 동작하지 않는 문제 수정,

content/javascript/plan.mdx
* tbody와 thead가 tr, td태그를 감싸주지 않아서 발생하는 에러문구 수정
=> :twisted_rightwards_arrows: 220905: 머지 충돌 수정, table에러 수정

content/javascript/registrations.mdx, content/masters/masthead.mdx, src/pageComponents/code-together/Course/Course.tsx, src/pageComponents/main/Culture/Culture.tsx, src/pageComponents/main/Place/Place.tsx, src/pages/index.tsx
=> 🔧 220905: v1.1.0 피드백 적용

src/pageComponents/javascript/GraduateReview/GraduateReview.docs.mdx, src/pageComponents/javascript/GraduateReview/GraduateReview.stories.tsx, src/pageComponents/javascript/Masthead/Masthead.stories.tsx, src/pageComponents/pre-course/Masthead/Masthead.stories.tsx, src/stories/Introduction.stories.mdx
* introduce 페이지 프리코스 추가
* 문서 링크 추가
* javascript 페이지에 필요한 문서 추가
* masthead 설명 docs추가
=> 📖 220916: 스토리북 문서 수정

src/assets/static/phrases.ts, src/components/HomeGlobalNavigationBar/HomeGlobalNavigationBar.tsx, src/components/HomeGlobalNavigationBar/MobileNavigationList/MobileNavigationList.test.tsx, src/components/HomeGlobalNavigationBar/MobileNavigationList/MobileNavigationList.tsx, src/components/LinkButton/LinkButton.tsx, src/pageComponents/main/CourseList/CourseList.test.tsx, src/pageComponents/main/CourseList/CourseList.tsx
=> 🔧 220916: 메인페이지 변경내용 적용

src/assets/static/phrases.ts, src/components/HomeGlobalNavigationBar/HomeGlobalNavigationBar.test.tsx, src/components/HomeGlobalNavigationBar/HomeGlobalNavigationBar.tsx, src/components/HomeGlobalNavigationBar/MobileNavigationList/MobileNavigationList.test.tsx, src/components/HomeGlobalNavigationBar/MobileNavigationList/MobileNavigationList.tsx, src/components/Interview/Interview.tsx, src/pageComponents/code-together/Masthead/Masthead.tsx, src/pageComponents/main/Culture/Culture.tsx, src/pageComponents/main/Place/Place.tsx
* popover동작 적용
* 변경된 bold/underline 사양 적용
* 사양변경에따른 테스트 코드 추가 및 제거
* 자바스크립트 페이지에서 인터뷰가 3개임에도 불구하고 RectangleNavigation에서 4개의 사각형을 보여주는 문제 해결
=> 🔧 220919: GNB 사양 적용, 버그 수정

src/components/HomeGlobalNavigationBar/HomeGlobalNavigationBar.tsx
* 마스터즈 링크에서 popover사이로 커서가 이동될때 popover가 사라지는 현상 수정
* popover가 마스터즈 링크 중앙에 위치하도록 변경
=> 🐛 220920: GNB 버그 수정

content/pre-course/masthead.mdx
=> 📖 220921 : 베타서버 피드백 반영(2)

src/pageComponents/pre-course/DetailCurriculum/Curriculum/Curriculum.tsx
=> 💄 220921: 커리큘럼 컴포넌트 스타일 수정

src/lib/context/GlobalHeader.tsx
* seo 관련 내용들을 name->property로 설정 속성 변경
=> 🔧 221007: 메타 속성 타입 변경

src/lib/context/GlobalHeader.tsx, src/pageComponents/pre-course/DetailCurriculum/Curriculum/Curriculum.tsx
* seo 관련 내용들을 name->property로 설정 속성 변경
=> 🚀 221007: 메타 속성 타입 변경

src/pageComponents/pre-course/DetailCurriculum/Curriculum/Curriculum.tsx, src/pageComponents/pre-course/DetailCurriculum/Curriculum/MasterInfo/MasterInfo.test.tsx, src/pageComponents/pre-course/DetailCurriculum/DetailCurriculum.test.mock.ts, src/pageComponents/pre-course/DetailCurriculum/DetailCurriculum.test.tsx
=> 🧪 221025: 테스트 코드 추가

src/pageComponents/pre-course/DetailCurriculum/Curriculum/MasterInfo/MasterInfo.test.tsx
* 이미지 파일면 변경으로 인해 통과 실패하는 케이스 수정
=> 🧪 221026: 테스트 코드 수정

content/code-together/course/clean-frontend/interviews.mdx, content/code-together/courseList.mdx, src/pageComponents/codeTogetherTemplate/DetailCurriculum/DetailCurriculum.stories.tsx, src/pageComponents/codeTogetherTemplate/GraduateReview/GraduateReview.stories.tsx, src/pageComponents/codeTogetherTemplate/GraduateReview/GraduateReview.tsx, src/pageComponents/codeTogetherTemplate/Masthead/Masthead.stories.tsx, src/pageComponents/codeTogetherTemplate/Registration/Registration.stories.tsx, src/pageComponents/codeTogetherTemplate/Registration/Registration.tsx, src/pageComponents/codeTogetherTemplate/TimeTable/TimeTable.stories.tsx, src/pageComponents/codeTogetherTemplate/TimeTable/TimeTable.tsx
=> 🐛 221213: 스토리북 에러 해결, 버튼 링크 수정

src/assets/static/phrases.ts
* faq페이지에서 보이지 않던 클린프론트엔드 문구 추가
=> :bug: 221215: 클린 프론트엔드 문구 추가

src/template/codeTogetherTemplate.tsx
=> 🔧 221222: GlobalHeader에 올바른 url이 설정되도록 수정

content/code-together/course/clean-swift/curriculum_part1.mdx, content/code-together/course/clean-swift/interviews.mdx, content/code-together/course/clean-swift/masthead.mdx, content/code-together/course/clean-swift/plan.mdx, content/code-together/course/clean-swift/registrations.mdx, content/code-together/courseList.mdx, content/faq/lists.mdx
=> 📖 221223: 코드투게더 클린 스위프트 페이지 생성

content/code-together/course/clean-frontend/registrations.mdx
- 기존 대기자 신청으로 가던 링크를 아래 루카스 링크로 수정
- https://lucas.codesquad.kr/main/course/clean-fe
=> 📖 230310: 코드투게더 - 클린 FE 페이지에 수강신청 안내 추가

src/assets/static/phrases.ts
=> 💬 230712: 푸터의 copyright문구와 주소 수정

content/masters/registration.mdx, src/pages/masters/index.tsx
2024년 대기자 모집을 위해 아래 링크 추가
[https://docs.google.com/forms/d/e/1FAIpQLSdjxAsrkmZmGS4FBCGmjmRhND9vq2HoxUy_8oOn9mPzV4cnvw/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSdjxAsrkmZmGS4FBCGmjmRhND9vq2HoxUy_8oOn9mPzV4cnvw/viewform?usp=sf_link)
=> 📖 230720: 마스터즈 - 2024 대기자 신청 링크 추가

content/masters/registration.mdx, src/assets/static/phrases.ts, src/pages/masters/index.tsx
* 2024년 대기자 모집을 위해 아래 링크 추가
* [https://docs.google.com/forms/d/e/1FAIpQLSdjxAsrkmZmGS4FBCGmjmRhND9vq2HoxUy_8oOn9mPzV4cnvw/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSdjxAsrkmZmGS4FBCGmjmRhND9vq2HoxUy_8oOn9mPzV4cnvw/viewform?usp=sf_link)
=> 🚀 230720: 마스터즈 - 2024 대기자 신청 링크 추가

src/assets/static/phrases.ts
- 클린 스위프트 > 만들면서 배우는 iOS 아키텍처
- 코드투게더 JS 과정 > 코드투게더 JS
=> 📖 230823: FAQ 태그명 수정

content/code-together/course/clean-react/curriculum_part1.mdx
=> 📖 230913: 코드투게더-클린리액트 커리큘럼 오타 수정

src/components/HomeGlobalNavigationBar/HomeGlobalNavigationBar.test.tsx, src/pageComponents/main/CourseList/CourseList.test.tsx
=> 🧪 231006: 테스트코드 수정

content/masters/registration.mdx
=> 📖 231012: 마스터즈 페이지에 설명회 영상링크 추가

content/code-together/course/clean-react/registrations.mdx
클린 리액트 프로그래밍 과정 페이지 문구 수정
- 대기자 모집 카드에서 과정 기간을 `미정`으로 수정
=> 📖 231026: 클린 리액트 프로그래밍 과정 페이지 문구 수정

content/code-together/course/clean-react/registrations.mdx, content/masters/registration.mdx
- 대기자 모집 카드에서 과정 기간을 `미정`으로 수정
=> 🚀  231026: 클린 리액트 프로그래밍 과정 페이지 문구 수정

gatsby-config.ts, package-lock.json, package.json
- 관련 패키지 업데이트
- gatsby-config.ts 수정
=> 🔧 231124: GA4 적용

src/components/Footer/Footer.tsx
=> 🔧 231226: Footer를 구성하는 컴포넌트  크기가 제대로 설정되지않아 불필요한 스크롤바가 생기는 문제 수정

src/components/Interview/Interview.tsx, src/pages/index.tsx
=> 🔧 240805: 중첩된 overflow옵션 제거, 인터뷰 컴포넌트에 overflow-x 옵션 설정

src/pageComponents/main/Master/Master.tsx
=> 🧑‍💻 240905: getByAltText때문에 잘 동작하지 않던 부분 수정

content/masters/registration.mdx, content/masters/schedule.mdx
- https://codesquaddev.atlassian.net/browse/WS-1725
=> 🧑‍💻 241008: 마스터즈 페이지 링크 수정

content/faq/lists.mdx
- https://codesquaddev.atlassian.net/browse/WS-1725
=> 🧑‍💻 241010: faq문구 수정

content/masters/curriculum_back.mdx, content/masters/curriculum_front.mdx, src/pageComponents/masters/DetailCurriculum/Curriculum/Curriculum.tsx
- https://codesquaddev.atlassian.net/browse/WS-1725
=> 🧑‍💻 241010: 마스터즈 커리큘럼 문구 수정

src/assets/static/phrases.ts
=> 🧑‍💻 241010: 버전, copyright문구 수정

content/masters/registration.mdx
=> 🧑‍💻 241029: 마스터즈 버튼 추가

content/masters/registration.mdx
- https://codesquaddev.atlassian.net/browse/WS-1956
=> 🧑‍💻 241118: 마스터즈 설명회 링크 추가

content/masters/registration.mdx
=> 🧑‍💻 241118: 마스터즈 테스트 연습하기 링크 추가

content/masters/registration.mdx, content/masters/schedule.mdx
=> 🧑‍💻 241127: 지원자 버튼 제거, 연습하기 문구 수정

content/masters/registration.mdx
=> 🧑‍💻 241204: 마스터즈 신청 버튼 마감

src/assets/static/phrases.ts
- https://codesquaddev.atlassian.net/browse/WS-2218
=> 🧑‍💻 250124: Copyright, 버전 정보 변경

src/assets/static/phrases.ts
- 1.4.9가 정확한 버전
- https://codesquaddev.atlassian.net/browse/WS-2218
=> 🧑‍💻 250124: 버전 문구 정정

content/code-together/_/curriculum_part1.mdx, content/code-together/_/interviews.mdx, content/code-together/_/masthead.mdx, content/code-together/_/plan.mdx, content/code-together/_/registrations.mdx, content/code-together/courses.mdx, content/faq/lists.mdx, content/masters/masthead.mdx, src/components/FAQ/FAQ.tsx, src/template/codeTogetherTemplate.tsx
- https://codesquaddev.atlassian.net/browse/WS-2599
=> 🧑‍💻 250331: 코드투게더 클린 프론트엔드 제거, 마스터즈 금액 문구 수정

.github/workflows/pipeline-beta.yml, .github/workflows/pipeline-master.yml
=> 🧑‍💻 250331: 액션 파일 버전 수정

content/masters/masthead.mdx, src/components/CourseInfo/InfoItem/InfoItem.tsx
=> 🧑‍💻 251001: 마스터즈 Masthead수정
